# Generated by Django 2.0.4 on 2018-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('cid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
              #  ('title4', models.CharField(max_length=100)),
               # ('title5', models.CharField(max_length=100)),
            ],
        ),
    ]
