# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
