# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180420_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adult',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child',
            field=models.IntegerField(),
        ),
    ]
